./configure \
--with-features=huge \
--with-compiledby="chakku" \
--enable-multibyte \
--enable-gui=gtk2 \
--enable-rubyinterp \
--enable-python3interp \
--enable-luainterp \
--with-lua-prefix=/usr \
--with-luajit \
--enable-gpm \
--enable-cscope \
--enable-fontset \
--enable-fail-if-missing
